# Generated by Django 6.0.4 on 2026-04-28 09:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
                (
                    "capacite",
                    models.IntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "equipement",
                    models.TextField(
                        blank=True,
                        help_text="Équipements disponibles (projecteur, tableau, etc.)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("OCCUPEE", "Occupée"),
                            ("MAINTENANCE", "En maintenance"),
                        ],
                        default="DISPONIBLE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours_plannifies",
                        to="core.professeur",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours_plannifies",
                        to="core.matiere",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours_plannifies",
                        to="core.promotion",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours_plannifies",
                        to="core.salle",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "salle"], name="core_cours_date_1e2d62_idx"
                    ),
                    models.Index(
                        fields=["date", "enseignant"], name="core_cours_date_ddfe3a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("salle", "date", "heure_debut", "heure_fin"),
                        name="unique_salle_creneau",
                    ),
                    models.UniqueConstraint(
                        fields=("enseignant", "date", "heure_debut", "heure_fin"),
                        name="unique_enseignant_creneau",
                    ),
                ],
            },
        ),
    ]
